[build]
  command = "vite build"
  publish = "dist/client"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server.mjs"
  status = 200

# Allow Facebook crawler
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
